from dotenv import load_dotenv
from typing_extensions import TypedDict
load_dotenv()
from typing import Optional,Literal
import os
from langgraph.graph import StateGraph,START,END
from langchain.chat_models import init_chat_model
from openai import OpenAI
from langchain_core.messages import SystemMessage,HumanMessage

client = OpenAI(
    api_key=os.getenv("GEMINI_API_KEY"),
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
)

llm = init_chat_model(
    model="gemini-3.7-flash",
    model_provider="google_genai"
)

class State(TypedDict):
    user_query: str
    llm_output: Optional[str]
    is_good: Optional[bool]

def evaluate_response(state:State) -> Literal["gemini_chatbot","endnode"]:
    print("\nevaluating response",state)
    messages = [
        SystemMessage(
            content="""
            You are a helpful assistant which will review the response generated by some llm. You will be provided with the user query and the output generated by the llm , your main goal is to judge the produced llm output bsed on relevance to the topic and detail and just reply with True or False.

            Example 1:- 
            user_query: What is the result of 2 + 2?
            llm_output: 2 + 2 is 4.
            A: True

            Example 2:
            user_query: What is the result of 2 + 2?
            llm_output: The capital of France is Paris.
            A: False

            Example 3:
            user_query: What is Python?
            llm_output: Python is a programming language commonly used
            for web development, automation, data analysis, and AI.
            A: True

            Example 4:
            user_query: What is Python?
            llm_output: Python is a type of snake.
            A: False
            """
        ),
         HumanMessage(
            content=f"""
            user_query: {state["user_query"]}
            llm_output: {state["llm_output"]}
            """
        )
    ]
    response = llm.invoke(messages)
    result = response.content[0]["text"].strip()
    
    if "True" in result:
        state["is_good"] = True
        return "endnode"
    return "gemini_chatbot"

def chatbot(state: State):
    print("Inside chatbot",state)
    response = client.chat.completions.create(
        model="gemini-3.1-flash-lite",
        messages=[
            {
                "role":"user",
                "content":state.get("user_query")
            }
        ]
    )
    state["llm_output"] = response.choices[0].message.content
    return state

def gemini_chatbot(state: State):
    print("\n\nInside gemini chatbot",state)
    response = client.chat.completions.create(
        model="gemini-3.5-flash-lite",
        messages=[
            {
                "role":"user",
                "content":state.get("user_query")
            }
        ]
    )
    state["llm_output"] = response.choices[0].message.content
    return state

def endnode(state:State):
    print("ending chat..",state)
    return state


graph_builder = StateGraph(State)

graph_builder.add_node("chatbot",chatbot)
graph_builder.add_node("endnode",endnode)
graph_builder.add_node("gemini_chatbot",gemini_chatbot)

graph_builder.add_edge(START,"chatbot")
graph_builder.add_conditional_edges(
    "chatbot",
    evaluate_response,
    {
        "endnode": "endnode",
        "gemini_chatbot": "gemini_chatbot",
    }
)
graph_builder.add_edge("gemini_chatbot","endnode")
graph_builder.add_edge("endnode",END)

graph = graph_builder.compile()

updated_state = graph.invoke(State({"user_query":"What is 2 + 2?"}))
print(updated_state.get("llm_output"))
